services:
  php:
    image: php:8.3-fpm
    container_name: api-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG=serverName=Docker
      - XDEBUG_TRIGGER=docker
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
    command: >
      sh -c "apt-get update &&
             apt-get install -y git unzip libzip-dev zip libonig-dev libxml2-dev libpng-dev libpq-dev libicu-dev &&
             php -m | grep xdebug || (pecl install -f xdebug && docker-php-ext-enable xdebug) &&
             docker-php-ext-install pdo pdo_mysql intl zip &&
             curl -sS https://getcomposer.org/installer | php &&
             mv composer.phar /usr/local/bin/composer &&
             composer install &&
             php-fpm"

  nginx:
    image: nginx:stable
    container_name: api-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
