services:
  php:
    image: php:8.3-fpm
    container_name: api-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - mysql
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
    command: >
      sh -c "apt-get update &&
             apt-get install -y git unzip libzip-dev zip libonig-dev libxml2-dev libpng-dev libpq-dev libicu-dev &&
             docker-php-ext-install pdo pdo_mysql intl zip &&
             curl -sS https://getcomposer.org/installer | php &&
             mv composer.phar /usr/local/bin/composer &&
             composer install &&
             php-fpm"

  nginx:
    image: nginx:stable
    container_name: api-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    container_name: api-db
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
